# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import airSensor_pb2 as airSensor__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BalancingServiceStub(object):
    """we must define all inputs/outputs with types defined in protobuf, thus, here.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAirData = channel.unary_unary(
                '/BalancingService/SendAirData',
                request_serializer=airSensor__pb2.RawMeteoData.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class BalancingServiceServicer(object):
    """we must define all inputs/outputs with types defined in protobuf, thus, here.
    """

    def SendAirData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BalancingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAirData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAirData,
                    request_deserializer=airSensor__pb2.RawMeteoData.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BalancingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BalancingService(object):
    """we must define all inputs/outputs with types defined in protobuf, thus, here.
    """

    @staticmethod
    def SendAirData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BalancingService/SendAirData',
            airSensor__pb2.RawMeteoData.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
