# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loadBalancer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sensors.rawTypes_pb2 as rawTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12loadBalancer.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0erawTypes.proto2\x99\x01\n\x15\x44\x61taProcessingService\x12;\n\x10ProcessMeteoData\x12\r.RawMeteoData\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x14ProcessPollutionData\x12\x11.RawPollutionData\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loadBalancer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAPROCESSINGSERVICE._serialized_start=68
  _DATAPROCESSINGSERVICE._serialized_end=221
# @@protoc_insertion_point(module_scope)
