# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pollutionSensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import data.rawTypes_pb2 as rawTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pollutionSensor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0erawTypes.proto2]\n\x19PollutionBalancingService\x12@\n\x11SendPollutionData\x12\x11.RawPollutionData\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pollutionSensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POLLUTIONBALANCINGSERVICE._serialized_start=70
  _POLLUTIONBALANCINGSERVICE._serialized_end=163
# @@protoc_insertion_point(module_scope)
