# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawTypes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erawTypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n\x10RawPollutionData\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x05\x12,\n\x08\x64\x61tetime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"c\n\x0cRawMeteoData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12,\n\x08\x64\x61tetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rawTypes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWPOLLUTIONDATA._serialized_start=51
  _RAWPOLLUTIONDATA._serialized_end=128
  _RAWMETEODATA._serialized_start=130
  _RAWMETEODATA._serialized_end=229
# @@protoc_insertion_point(module_scope)
