# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n\x06Result\x12\x10\n\x08wellness\x18\x01 \x01(\x02\x12\x11\n\tpollution\x18\x02 \x01(\x02\x12,\n\x08\x64\x61tetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2B\n\x0eResultsService\x12\x30\n\x0bSendResults\x12\x07.Result\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULT._serialized_start=77
  _RESULT._serialized_end=168
  _RESULTSSERVICE._serialized_start=170
  _RESULTSSERVICE._serialized_end=236
# @@protoc_insertion_point(module_scope)
