# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import processedTypes_pb2 as processedTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14processedTypes.proto\"D\n\x06Result\x12\x1b\n\x08wellness\x18\x01 \x01(\x0b\x32\t.Wellness\x12\x1d\n\tpollution\x18\x02 \x01(\x0b\x32\n.Pollution2B\n\x0eResultsService\x12\x30\n\x0bSendResults\x12\x07.Result\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULT._serialized_start=66
  _RESULT._serialized_end=134
  _RESULTSSERVICE._serialized_start=136
  _RESULTSSERVICE._serialized_end=202
# @@protoc_insertion_point(module_scope)
