# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terminal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import data.processedTypes_pb2 as processedTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eterminal.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14processedTypes.proto\"\x1b\n\x0b\x43onnectionT\x12\x0c\n\x04port\x18\x01 \x01(\x05\"r\n\x06Result\x12\x1b\n\x08wellness\x18\x01 \x01(\x0b\x32\t.Wellness\x12\x1d\n\tpollution\x18\x02 \x01(\x0b\x32\n.Pollution\x12,\n\x08\x64\x61tetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2P\n\x12\x43onnectionTService\x12:\n\x10SubscribeToProxy\x12\x0c.ConnectionT\x1a\x16.google.protobuf.Empty\"\x00\x32\x42\n\x0eResultsService\x12\x30\n\x0bSendResults\x12\x07.Result\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terminal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTIONT._serialized_start=102
  _CONNECTIONT._serialized_end=129
  _RESULT._serialized_start=131
  _RESULT._serialized_end=245
  _CONNECTIONTSERVICE._serialized_start=247
  _CONNECTIONTSERVICE._serialized_end=327
  _RESULTSSERVICE._serialized_start=329
  _RESULTSSERVICE._serialized_end=395
# @@protoc_insertion_point(module_scope)
