# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userTerminal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12userTerminal.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\x0b\x43onnectionT\x12\x0c\n\x04port\x18\x01 \x01(\x05\x32P\n\x12\x43onnectionTService\x12:\n\x10SubscribeToProxy\x12\x0c.ConnectionT\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userTerminal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTIONT._serialized_start=51
  _CONNECTIONT._serialized_end=78
  _CONNECTIONTSERVICE._serialized_start=80
  _CONNECTIONTSERVICE._serialized_end=160
# @@protoc_insertion_point(module_scope)
